baseURL = "https://afr-dt.github.io/"
languageCode = 'en-us'
title = "Perfil de Alejandro"

[module]
[[module.imports]]
path = "github.com/lordmathis/hugo-theme-nightfall"

[pagination]
pagerSize = 3

[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
user = "afr-dt"
hostname = "afr-dt.github.io"
email = "aleksgnu@gmail.com"
description = "Backend & DevOps Engineer"
openLinksInNewTab = true


[menu]
[[menu.header]]
name = "Sobre m√≠"
identifier = "about"
url = "/about/"
weight = 2

[[menu.header]]
name = "Blog"
identifier = "blog"
url = "/post/"
weight = 3

[params.author]
name = "Alejandro Flores"
avatar = ""
email = "aleksgnu@gmail.com"

# Social links
[[params.social]]
name = "github"
url = "https://github.com/afr-dt"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/afr-dt"

[[params.social]]
name = "twitter"
url = "https://twitter.com/afr_dt"

[[params.social]]
name = "email"
url = "mailto:aleksgnu@gmail.com"
